# fly.toml app configuration file generated for vlcek-mysql-db on 2023-05-01T10:35:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vlcek-mysql-db"
kill_signal = "SIGINT"
kill_timeout = 5

primary_region = "ams"


[processes]
  app = "--datadir /data/mysql --default-authentication-plugin mysql_native_password --performance-schema=OFF --innodb-buffer-pool-size 64M"

[mounts]
  source="mysqldata"
  destination="/data"

[env]
  MYSQL_DATABASE = "some_db"
  MYSQL_USER = "non_root_user"

[build]
  image = "mysql:8.0.32"
